name = "cf-instagram-feed"
main = "./.output/server/index.mjs"
compatibility_date = "2024-07-12"
env = { }

rules = [
  { type = "ESModule", globs = ["**/*.js", "**/*.mjs"]},
]

[site]
bucket = ".output/public"

[triggers]
crons = [ ]

# [secrets]
# NITRO_ACCESS_TOKEN
